# Generated by Django 5.2.11 on 2026-10-02 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_grupo_administradores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="data_fim",
            field=models.DateField(
                help_text="Data de saída da chácara (deve ser posterior à data de chegada).",
                verbose_name="Data de Fim",
            ),
        ),
        migrations.CreateModel(
            name="HistoricoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("RECUSADA", "Recusada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        help_text="Status antes da alteração (vazio na criação do pedido).",
                        max_length=20,
                        verbose_name="Status Anterior",
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("RECUSADA", "Recusada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        help_text="Status depois da alteração.",
                        max_length=20,
                        verbose_name="Status Novo",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora da alteração.",
                        verbose_name="Data",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True,
                        help_text="Motivo ou detalhe da alteração.",
                        verbose_name="Observação",
                    ),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que fez a alteração.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        help_text="Reserva cujo status foi alterado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="website.reserva",
                        verbose_name="Reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Reserva",
                "verbose_name_plural": "Históricos de Reserva",
                "ordering": ["-data"],
            },
        ),
    ]
