# Generated by Django 5.2.11 on 2026-10-02 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_reserva_data_fim_historicoreserva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="analise_ia",
            field=models.JSONField(
                blank=True,
                help_text="Resumo do pedido gerado automaticamente pelo Gemini (apoio à administradora).",
                null=True,
                verbose_name="Análise da IA",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="analise_ia_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que a análise da IA foi gerada.",
                null=True,
                verbose_name="Análise da IA em",
            ),
        ),
        migrations.CreateModel(
            name="UsoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CHAT", "Chat (assistente)"),
                            ("ANALISE", "Análise de pedido"),
                        ],
                        help_text="Chat com o assistente ou análise automática de pedido.",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "tokens_entrada",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="prompt_token_count: instrução + histórico + mensagem.",
                        verbose_name="Tokens de Entrada",
                    ),
                ),
                (
                    "tokens_saida",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tokens gerados pelo modelo (resposta + raciocínio).",
                        verbose_name="Tokens de Saída",
                    ),
                ),
                (
                    "custo_usd",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Calculado automaticamente com os preços do settings.",
                        max_digits=12,
                        verbose_name="Custo (US$)",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora da chamada.",
                        verbose_name="Data",
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reserva analisada (só nas análises de pedido).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.reserva",
                        verbose_name="Reserva",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quem fez a chamada (vazio para visitante).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso da IA",
                "verbose_name_plural": "Usos da IA",
                "ordering": ["-data"],
            },
        ),
    ]
